# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Update npm dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm run test

  deploy-job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    steps:
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli 

      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: Update npm dependencies
          command: npm install

      - run: npm run build

      - run :
          name: deploy to AWS
          command: aws configure set default.s3.signature_version s3v4 && aws configure set default.region eu-central-1 && aws s3 sync build s3://flystr.com/ --delete

      - run :
          name: Purge CloudFlare Cache
          command: curl -X DELETE https://api.cloudflare.com/client/v4/zones/0c24d4d9078059f3168eae12ecf6e0e3/purge_cache -H X-Auth-Email:dev@maass.co -H X-Auth-Key:325c9f694eece58fd4ccde6301524dd2e0990 -H Content-Type:application/json  --data '{"purge_everything":true}'

     - run:
          name: Install prep
          command: sudo npm install -g prep

      - run:
          name: Create Snapshots
          command: prep snaps
          
      - run:
          name: Rename Index
          command: mv snaps/index.html snaps/_index.html

      - run :
          name: deploy snapshots to AWS
          command: aws configure set default.s3.signature_version s3v4 && aws configure set default.region eu-central-1 && aws s3 sync snaps s3://flystr.com/ 


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master